from .battery import battery
from .clock import clock
from .currentlayout import currentlayout
from .groupbox import groupbox
from .observer import observers
from .spotify import spotify
from .volume import volume
from .windowname import windowname
from .wlan import wlan
