* Deploying

* Post-deployment

ZNC isn't fully turn-key. After deployment, we need to:

- Generate a ZNC SSL certificate
- Tell ZNC the SASL username and password

** Generate ZNC Cert

SSL is needed to encrypt communications between the IRC client and the ZNC server.

After deploying with NixOps, the =/var/lib/znc/znc.pem= will be empty and needs to be
generated.

*** Connect to the Server
#+begin_src shell
  nixops ssh -d $server-name $server-name
#+end_src

*** Generate Certificate
#+begin_src shell
  cd /var/lib/znc
  openssl req -nodes -newkey rsa:2048 -keyout znc.pem -x509 -days 3650 -out znc.pem -subj "/CN=ldlework"
#+end_src

** Establish SASL Credentials

The easiest way to setup ZNC SASL is to just use Weechat.

- Create a weechat connection to ZNC
- Set the SASL username and password

Replace the following pseudo-variables with the relevant values when using the
examples below:

- =$server-name= the nixops server name
- =$server-ip= the nixops server ip address
- =$server-port= the port of the ZNC service
- =$znc-username= the znc username
- =$znc-password= the znc password
- =$network-name= the znc network name
- =$sasl-username= the nickserv username
- =$sasl-password= the nickserv password

*** Create new Weechat connection

#+begin_src text
  /server add $server-name $server-ip/$server-port
  /set irc.server.$server-name.username $znc-username/$network-name
  /set irc.server.$server-name.password $znc-password
  /set irc.server.$server-name.ssl on
  /set irc.server.$server-name.ssl_verify off
  /msg *sasl set $sasl-username/$network-name $sasl-password
#+end_src

